/* Generated by gbrecomp */
#ifndef NewAdventuresofSonic_H
#define NewAdventuresofSonic_H

#include "gbrt.h"

const GBConfig* NewAdventuresofSonic_default_config(void);
void NewAdventuresofSonic_run(GBContext* ctx);
void NewAdventuresofSonic_init(GBContext* ctx);
int NewAdventuresofSonic_main(int argc, char* argv[]);

#endif
