/* Generated by gbrecomp from NewAdventuresofSonic */
#include "NewAdventuresofSonic_internal.h"

/* Shared body at 14:7ffe */
static void body_14_7ffe(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_14_7ffe:
    /* warning: fallthrough to unanalyzed code at 0x7ffb in bank 20 */
    return;
}

void func_14_7ffe(GBContext* ctx) {
    body_14_7ffe(ctx);
}

/* Shared body at 15:4012 */
static void body_15_4012(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x4012: goto loc_15_4012;
        case 0x4013: goto pc_4013;
        case 0x4014: goto pc_4014;
        case 0x4015: goto loc_15_4015;
        default: break;
    }

loc_15_4012:
    /* LD A,(HL) */
    /* 15:4012 */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x4013;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,(HL) */
pc_4013:
    /* 15:4013 */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x4014;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_4014:
    /* 15:4014 */     gbrt_timed_rst(ctx, 0x38, 0x4015);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_15_4015:
    /* JP $99ff */
    /* 15:4015 */     gbrt_timed_jump(ctx, 0x99ff, 16); return;
    if (ctx->single_step_mode) return;
}

void func_15_4012(GBContext* ctx) {
    body_15_4012(ctx);
}

