/* Generated by gbrecomp from NewAdventuresofSonic */
#include "NewAdventuresofSonic_internal.h"

/* Shared body at 0e:7ffe */
static void body_0e_7ffe(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_0e_7ffe:
    /* warning: fallthrough to unanalyzed code at 0x7fd5 in bank 14 */
    return;
}

void func_0e_7ffe(GBContext* ctx) {
    body_0e_7ffe(ctx);
}

/* Shared body at 0f:7ffe */
static void body_0f_7ffe(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_0f_7ffe:
    /* warning: fallthrough to unanalyzed code at 0x7fd5 in bank 15 */
    return;
}

void func_0f_7ffe(GBContext* ctx) {
    body_0f_7ffe(ctx);
}

/* Shared body at 10:7ffe */
static void body_10_7ffe(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_10_7ffe:
    /* warning: fallthrough to unanalyzed code at 0x7fd5 in bank 16 */
    return;
}

void func_10_7ffe(GBContext* ctx) {
    body_10_7ffe(ctx);
}

/* Shared body at 11:7fec */
static void body_11_7fec(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x7fec: goto loc_11_7fec;
        case 0x7fed: goto pc_7fed;
        case 0x7fee: goto loc_11_7fee;
        case 0x7fef: goto loc_11_7fef;
        case 0x7ff0: goto pc_7ff0;
        default: break;
    }

loc_11_7fec:
    /* NOP */
    /* 11:7fec */     /* NOP */
    ctx->pc = 0x7fed;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LDH A,($FF00+$d7) */
pc_7fed:
    /* 11:7fed */     gb_tick(ctx, 11);
    ctx->a = gb_read8(ctx, GB_HRAM_BASE + 0x57);
    gb_tick(ctx, 1);
    ctx->pc = 0x7fef;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_11_7fef; /* fallthrough */
loc_11_7fee:
    /* RST $10 */
    /* 11:7fee */     gbrt_timed_rst(ctx, 0x10, 0x7fef);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_10(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_11_7fef:
    /* LD A,A */
    /* 11:7fef */     ctx->a = ctx->a;
    ctx->pc = 0x7ff0;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RETI */
pc_7ff0:
    /* 11:7ff0 */     gbrt_timed_reti(ctx);
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x7ff1 in bank 17 */
    return;
}

void func_11_7fec(GBContext* ctx) {
    body_11_7fec(ctx);
}

void func_11_7fee(GBContext* ctx) {
    body_11_7fec(ctx);
}

/* Shared body at 11:7ffe */
static void body_11_7ffe(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_11_7ffe:
    /* warning: fallthrough to unanalyzed code at 0x7ff1 in bank 17 */
    return;
}

void func_11_7ffe(GBContext* ctx) {
    body_11_7ffe(ctx);
}

/* Shared body at 12:7fd4 */
static void body_12_7fd4(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x7fd4: goto loc_12_7fd4;
        case 0x7fd5: goto loc_12_7fd5;
        case 0x7fd6: goto pc_7fd6;
        case 0x7fd7: goto pc_7fd7;
        case 0x7fd8: goto pc_7fd8;
        case 0x7fd9: goto pc_7fd9;
        case 0x7fda: goto pc_7fda;
        case 0x7fdb: goto pc_7fdb;
        case 0x7fdc: goto pc_7fdc;
        case 0x7fdd: goto pc_7fdd;
        case 0x7fde: goto pc_7fde;
        case 0x7fdf: goto pc_7fdf;
        case 0x7fe0: goto pc_7fe0;
        case 0x7fe1: goto pc_7fe1;
        case 0x7fe2: goto pc_7fe2;
        case 0x7fe3: goto pc_7fe3;
        case 0x7fe4: goto pc_7fe4;
        case 0x7fe5: goto pc_7fe5;
        case 0x7fe6: goto pc_7fe6;
        case 0x7fe7: goto pc_7fe7;
        case 0x7fe8: goto pc_7fe8;
        case 0x7feb: goto pc_7feb;
        case 0x7fee: goto loc_12_7fee;
        case 0x7fef: goto pc_7fef;
        case 0x7ff1: goto pc_7ff1;
        case 0x7ff2: goto pc_7ff2;
        case 0x7ff3: goto pc_7ff3;
        case 0x7ff5: goto pc_7ff5;
        case 0x7ff6: goto pc_7ff6;
        case 0x7ff7: goto pc_7ff7;
        case 0x7ff8: goto pc_7ff8;
        case 0x7ff9: goto pc_7ff9;
        case 0x7ffa: goto pc_7ffa;
        default: break;
    }

loc_12_7fd4:
    /* RET Z */
    /* 12:7fd4 */     if (ctx->f_z) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* Z */
    gbrt_timed_jump(ctx, 0x7fd5, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_12_7fd5:
    /* LD A,A */
    /* 12:7fd5 */     ctx->a = ctx->a;
    ctx->pc = 0x7fd6;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7fd6:
    /* 12:7fd6 */     /* NOP */
    ctx->pc = 0x7fd7;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7fd7:
    /* 12:7fd7 */     /* NOP */
    ctx->pc = 0x7fd8;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7fd8:
    /* 12:7fd8 */     /* NOP */
    ctx->pc = 0x7fd9;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7fd9:
    /* 12:7fd9 */     /* NOP */
    ctx->pc = 0x7fda;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7fda:
    /* 12:7fda */     /* NOP */
    ctx->pc = 0x7fdb;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7fdb:
    /* 12:7fdb */     /* NOP */
    ctx->pc = 0x7fdc;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7fdc:
    /* 12:7fdc */     /* NOP */
    ctx->pc = 0x7fdd;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7fdd:
    /* 12:7fdd */     /* NOP */
    ctx->pc = 0x7fde;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7fde:
    /* 12:7fde */     /* NOP */
    ctx->pc = 0x7fdf;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7fdf:
    /* 12:7fdf */     /* NOP */
    ctx->pc = 0x7fe0;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7fe0:
    /* 12:7fe0 */     /* NOP */
    ctx->pc = 0x7fe1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7fe1:
    /* 12:7fe1 */     /* NOP */
    ctx->pc = 0x7fe2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7fe2:
    /* 12:7fe2 */     /* NOP */
    ctx->pc = 0x7fe3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7fe3:
    /* 12:7fe3 */     /* NOP */
    ctx->pc = 0x7fe4;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7fe4:
    /* 12:7fe4 */     /* NOP */
    ctx->pc = 0x7fe5;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7fe5:
    /* 12:7fe5 */     /* NOP */
    ctx->pc = 0x7fe6;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7fe6:
    /* 12:7fe6 */     /* NOP */
    ctx->pc = 0x7fe7;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7fe7:
    /* 12:7fe7 */     /* NOP */
    ctx->pc = 0x7fe8;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$f000 */
pc_7fe8:
    /* 12:7fe8 */     ctx->bc = 0xf000;
    ctx->pc = 0x7feb;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CALL NC,$d67f */
pc_7feb:
    /* 12:7feb */     if (!ctx->f_c) {
        gbrt_timed_call(ctx, 0xd67f, 0x7fee);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        return;
    } /* NC */
    gbrt_timed_jump(ctx, 0x7fee, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_12_7fee:
    /* LD A,A */
    /* 12:7fee */     ctx->a = ctx->a;
    ctx->pc = 0x7fef;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* AND $7f */
pc_7fef:
    /* 12:7fef */     gb_and8(ctx, 0x7f);
    ctx->pc = 0x7ff1;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7ff1:
    /* 12:7ff1 */     /* NOP */
    ctx->pc = 0x7ff2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7ff2:
    /* 12:7ff2 */     gb_rrca(ctx);
    ctx->pc = 0x7ff3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,SP+7 */
pc_7ff3:
    /* 12:7ff3 */     gbrt_timed_ld_hl_sp_n(ctx, 0x7ff4);
    ctx->pc = 0x7ff5;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC DE */
pc_7ff5:
    /* 12:7ff5 */     gbrt_timed_dec16(ctx, &ctx->de);
    ctx->pc = 0x7ff6;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,C */
pc_7ff6:
    /* 12:7ff6 */     ctx->b = ctx->c;
    ctx->pc = 0x7ff7;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,B */
pc_7ff7:
    /* 12:7ff7 */     ctx->c = ctx->b;
    ctx->pc = 0x7ff8;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7ff8:
    /* 12:7ff8 */     /* NOP */
    ctx->pc = 0x7ff9;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7ff9:
    /* 12:7ff9 */     /* NOP */
    ctx->pc = 0x7ffa;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7ffa:
    /* 12:7ffa */     /* NOP */
    ctx->pc = 0x7ffb;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x7ffb in bank 18 */
    return;
}

void func_12_7fd4(GBContext* ctx) {
    body_12_7fd4(ctx);
}

/* Shared body at 12:7ffe */
static void body_12_7ffe(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_12_7ffe:
    /* warning: fallthrough to unanalyzed code at 0x7ffb in bank 18 */
    return;
}

void func_12_7ffe(GBContext* ctx) {
    body_12_7ffe(ctx);
}

/* Shared body at 13:4000 */
static void body_13_4000(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x4000: goto loc_13_4000;
        case 0x4001: goto pc_4001;
        case 0x4004: goto pc_4004;
        case 0x4005: goto pc_4005;
        case 0x4006: goto pc_4006;
        case 0x4007: goto pc_4007;
        case 0x400a: goto pc_400a;
        case 0x400b: goto pc_400b;
        case 0x400c: goto pc_400c;
        case 0x400f: goto pc_400f;
        case 0x4011: goto pc_4011;
        case 0x4014: goto pc_4014;
        case 0x4016: goto pc_4016;
        case 0x4018: goto pc_4018;
        case 0x401b: goto pc_401b;
        default: break;
    }

loc_13_4000:
    /* XOR A */
    /* 13:4000 */     gb_xor8(ctx, ctx->a);
    ctx->pc = 0x4001;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,$c585 */
pc_4001:
    /* 13:4001 */     ctx->hl = GB_WRAM0_BASE + 0x0585;
    ctx->pc = 0x4004;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL+),A */
pc_4004:
    /* 13:4004 */     gbrt_timed_hl_write_auto(ctx, ctx->a, 1);
    ctx->pc = 0x4005;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),A */
pc_4005:
    /* 13:4005 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x4006;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* XOR A */
pc_4006:
    /* 13:4006 */     gb_xor8(ctx, ctx->a);
    ctx->pc = 0x4007;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,$c583 */
pc_4007:
    /* 13:4007 */     ctx->hl = GB_WRAM0_BASE + 0x0583;
    ctx->pc = 0x400a;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL+),A */
pc_400a:
    /* 13:400a */     gbrt_timed_hl_write_auto(ctx, ctx->a, 1);
    ctx->pc = 0x400b;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),A */
pc_400b:
    /* 13:400b */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x400c;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,$c588 */
pc_400c:
    /* 13:400c */     ctx->hl = GB_WRAM0_BASE + 0x0588;
    ctx->pc = 0x400f;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),$00 */
pc_400f:
    /* 13:400f */     gb_tick(ctx, 11);
    gb_write8(ctx, ctx->hl, 0x00);
    gb_tick(ctx, 1);
    ctx->pc = 0x4011;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,$c587 */
pc_4011:
    /* 13:4011 */     ctx->hl = GB_WRAM0_BASE + 0x0587;
    ctx->pc = 0x4014;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),$00 */
pc_4014:
    /* 13:4014 */     gb_tick(ctx, 11);
    gb_write8(ctx, ctx->hl, 0x00);
    gb_tick(ctx, 1);
    ctx->pc = 0x4016;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,$13 */
pc_4016:
    /* 13:4016 */     ctx->e = 0x13;
    ctx->pc = 0x4018;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,$401e */
pc_4018:
    /* 13:4018 */     ctx->hl = 0x401e;
    ctx->pc = 0x401b;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JP $0008 */
pc_401b:
    /* 13:401b */     gbrt_timed_jump(ctx, 0x0008, 16); return;
    if (ctx->single_step_mode) return;
}

void func_13_4000(GBContext* ctx) {
    body_13_4000(ctx);
}

/* Shared body at 13:4002 */
static void body_13_4002(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x4002: goto loc_13_4002;
        case 0x4003: goto pc_4003;
        case 0x4004: goto pc_4004;
        case 0x4005: goto pc_4005;
        case 0x4006: goto pc_4006;
        case 0x4007: goto pc_4007;
        case 0x400a: goto pc_400a;
        case 0x400b: goto pc_400b;
        case 0x400c: goto pc_400c;
        case 0x400f: goto pc_400f;
        case 0x4011: goto pc_4011;
        case 0x4014: goto pc_4014;
        case 0x4016: goto pc_4016;
        case 0x4018: goto pc_4018;
        case 0x401b: goto pc_401b;
        default: break;
    }

loc_13_4002:
    /* ADD A,L */
    /* 13:4002 */     gb_add8(ctx, ctx->l);
    ctx->pc = 0x4003;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* PUSH BC */
pc_4003:
    /* 13:4003 */     gbrt_timed_push16(ctx, ctx->bc);
    ctx->pc = 0x4004;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL+),A */
pc_4004:
    /* 13:4004 */     gbrt_timed_hl_write_auto(ctx, ctx->a, 1);
    ctx->pc = 0x4005;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),A */
pc_4005:
    /* 13:4005 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x4006;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* XOR A */
pc_4006:
    /* 13:4006 */     gb_xor8(ctx, ctx->a);
    ctx->pc = 0x4007;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,$c583 */
pc_4007:
    /* 13:4007 */     ctx->hl = GB_WRAM0_BASE + 0x0583;
    ctx->pc = 0x400a;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL+),A */
pc_400a:
    /* 13:400a */     gbrt_timed_hl_write_auto(ctx, ctx->a, 1);
    ctx->pc = 0x400b;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),A */
pc_400b:
    /* 13:400b */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x400c;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,$c588 */
pc_400c:
    /* 13:400c */     ctx->hl = GB_WRAM0_BASE + 0x0588;
    ctx->pc = 0x400f;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),$00 */
pc_400f:
    /* 13:400f */     gb_tick(ctx, 11);
    gb_write8(ctx, ctx->hl, 0x00);
    gb_tick(ctx, 1);
    ctx->pc = 0x4011;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,$c587 */
pc_4011:
    /* 13:4011 */     ctx->hl = GB_WRAM0_BASE + 0x0587;
    ctx->pc = 0x4014;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),$00 */
pc_4014:
    /* 13:4014 */     gb_tick(ctx, 11);
    gb_write8(ctx, ctx->hl, 0x00);
    gb_tick(ctx, 1);
    ctx->pc = 0x4016;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,$13 */
pc_4016:
    /* 13:4016 */     ctx->e = 0x13;
    ctx->pc = 0x4018;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,$401e */
pc_4018:
    /* 13:4018 */     ctx->hl = 0x401e;
    ctx->pc = 0x401b;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JP $0008 */
pc_401b:
    /* 13:401b */     gbrt_timed_jump(ctx, 0x0008, 16); return;
    if (ctx->single_step_mode) return;
}

void func_13_4002(GBContext* ctx) {
    body_13_4002(ctx);
}

/* Shared body at 13:401e */
static void body_13_401e(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x401e: goto loc_13_401e;
        case 0x4021: goto pc_4021;
        case 0x4023: goto pc_4023;
        case 0x4026: goto pc_4026;
        case 0x4028: goto loc_13_4028;
        case 0x402b: goto pc_402b;
        case 0x402d: goto pc_402d;
        default: break;
    }

loc_13_401e:
    /* LD HL,$c58a */
    /* 13:401e */     ctx->hl = GB_WRAM0_BASE + 0x058a;
    ctx->pc = 0x4021;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),$00 */
pc_4021:
    /* 13:4021 */     gb_tick(ctx, 11);
    gb_write8(ctx, ctx->hl, 0x00);
    gb_tick(ctx, 1);
    ctx->pc = 0x4023;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,$c589 */
pc_4023:
    /* 13:4023 */     ctx->hl = GB_WRAM0_BASE + 0x0589;
    ctx->pc = 0x4026;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),$00 */
pc_4026:
    /* 13:4026 */     gb_tick(ctx, 11);
    gb_write8(ctx, ctx->hl, 0x00);
    gb_tick(ctx, 1);
    ctx->pc = 0x4028;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_13_4028:
    /* LD HL,$c58b */
    /* 13:4028 */     ctx->hl = GB_WRAM0_BASE + 0x058b;
    ctx->pc = 0x402b;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),$03 */
pc_402b:
    /* 13:402b */     gb_tick(ctx, 11);
    gb_write8(ctx, ctx->hl, 0x03);
    gb_tick(ctx, 1);
    ctx->pc = 0x402d;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RET */
pc_402d:
    /* 13:402d */     gbrt_timed_ret(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_13_401e(GBContext* ctx) {
    body_13_401e(ctx);
}

void func_13_4028(GBContext* ctx) {
    body_13_401e(ctx);
}

/* Shared body at 13:7fce */
static void body_13_7fce(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x7fce: goto loc_13_7fce;
        case 0x7fcf: goto pc_7fcf;
        case 0x7fd0: goto pc_7fd0;
        case 0x7fd1: goto pc_7fd1;
        case 0x7fd2: goto pc_7fd2;
        case 0x7fd3: goto pc_7fd3;
        case 0x7fd4: goto pc_7fd4;
        case 0x7fd5: goto pc_7fd5;
        case 0x7fd6: goto pc_7fd6;
        case 0x7fd7: goto pc_7fd7;
        case 0x7fd8: goto pc_7fd8;
        case 0x7fd9: goto pc_7fd9;
        case 0x7fda: goto pc_7fda;
        case 0x7fdb: goto pc_7fdb;
        case 0x7fdc: goto pc_7fdc;
        case 0x7fdd: goto pc_7fdd;
        case 0x7fde: goto pc_7fde;
        case 0x7fdf: goto pc_7fdf;
        case 0x7fe0: goto pc_7fe0;
        case 0x7fe1: goto pc_7fe1;
        case 0x7fe2: goto pc_7fe2;
        case 0x7fe3: goto pc_7fe3;
        case 0x7fe4: goto pc_7fe4;
        case 0x7fe5: goto pc_7fe5;
        case 0x7fe6: goto pc_7fe6;
        case 0x7fe7: goto pc_7fe7;
        case 0x7fe8: goto pc_7fe8;
        case 0x7fe9: goto pc_7fe9;
        case 0x7fea: goto pc_7fea;
        case 0x7feb: goto pc_7feb;
        case 0x7fec: goto pc_7fec;
        case 0x7fed: goto pc_7fed;
        case 0x7fee: goto loc_13_7fee;
        case 0x7ff1: goto pc_7ff1;
        case 0x7ff3: goto pc_7ff3;
        case 0x7ff6: goto pc_7ff6;
        case 0x7ff8: goto pc_7ff8;
        case 0x7ffb: goto pc_7ffb;
        case 0x7ffd: goto pc_7ffd;
        default: break;
    }

loc_13_7fce:
    /* RRCA */
    /* 13:7fce */     gb_rrca(ctx);
    ctx->pc = 0x7fcf;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7fcf:
    /* 13:7fcf */     gb_rrca(ctx);
    ctx->pc = 0x7fd0;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7fd0:
    /* 13:7fd0 */     gb_rrca(ctx);
    ctx->pc = 0x7fd1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7fd1:
    /* 13:7fd1 */     gb_rrca(ctx);
    ctx->pc = 0x7fd2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7fd2:
    /* 13:7fd2 */     gb_rrca(ctx);
    ctx->pc = 0x7fd3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7fd3:
    /* 13:7fd3 */     gb_rrca(ctx);
    ctx->pc = 0x7fd4;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7fd4:
    /* 13:7fd4 */     gb_rrca(ctx);
    ctx->pc = 0x7fd5;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7fd5:
    /* 13:7fd5 */     gb_rrca(ctx);
    ctx->pc = 0x7fd6;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7fd6:
    /* 13:7fd6 */     gb_rrca(ctx);
    ctx->pc = 0x7fd7;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7fd7:
    /* 13:7fd7 */     gb_rrca(ctx);
    ctx->pc = 0x7fd8;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7fd8:
    /* 13:7fd8 */     gb_rrca(ctx);
    ctx->pc = 0x7fd9;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7fd9:
    /* 13:7fd9 */     gb_rrca(ctx);
    ctx->pc = 0x7fda;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7fda:
    /* 13:7fda */     gb_rrca(ctx);
    ctx->pc = 0x7fdb;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7fdb:
    /* 13:7fdb */     gb_rrca(ctx);
    ctx->pc = 0x7fdc;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7fdc:
    /* 13:7fdc */     gb_rrca(ctx);
    ctx->pc = 0x7fdd;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7fdd:
    /* 13:7fdd */     gb_rrca(ctx);
    ctx->pc = 0x7fde;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7fde:
    /* 13:7fde */     gb_rrca(ctx);
    ctx->pc = 0x7fdf;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7fdf:
    /* 13:7fdf */     gb_rrca(ctx);
    ctx->pc = 0x7fe0;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7fe0:
    /* 13:7fe0 */     gb_rrca(ctx);
    ctx->pc = 0x7fe1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7fe1:
    /* 13:7fe1 */     gb_rrca(ctx);
    ctx->pc = 0x7fe2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7fe2:
    /* 13:7fe2 */     gb_rrca(ctx);
    ctx->pc = 0x7fe3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7fe3:
    /* 13:7fe3 */     gb_rrca(ctx);
    ctx->pc = 0x7fe4;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7fe4:
    /* 13:7fe4 */     gb_rrca(ctx);
    ctx->pc = 0x7fe5;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7fe5:
    /* 13:7fe5 */     gb_rrca(ctx);
    ctx->pc = 0x7fe6;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7fe6:
    /* 13:7fe6 */     gb_rrca(ctx);
    ctx->pc = 0x7fe7;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7fe7:
    /* 13:7fe7 */     gb_rrca(ctx);
    ctx->pc = 0x7fe8;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7fe8:
    /* 13:7fe8 */     gb_rrca(ctx);
    ctx->pc = 0x7fe9;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7fe9:
    /* 13:7fe9 */     gb_rrca(ctx);
    ctx->pc = 0x7fea;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7fea:
    /* 13:7fea */     gb_rrca(ctx);
    ctx->pc = 0x7feb;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7feb:
    /* 13:7feb */     gb_rrca(ctx);
    ctx->pc = 0x7fec;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7fec:
    /* 13:7fec */     gb_rrca(ctx);
    ctx->pc = 0x7fed;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7fed:
    /* 13:7fed */     gb_rrca(ctx);
    ctx->pc = 0x7fee;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_13_7fee:
    /* LD HL,$c587 */
    /* 13:7fee */     ctx->hl = GB_WRAM0_BASE + 0x0587;
    ctx->pc = 0x7ff1;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),$00 */
pc_7ff1:
    /* 13:7ff1 */     gb_tick(ctx, 11);
    gb_write8(ctx, ctx->hl, 0x00);
    gb_tick(ctx, 1);
    ctx->pc = 0x7ff3;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,$c588 */
pc_7ff3:
    /* 13:7ff3 */     ctx->hl = GB_WRAM0_BASE + 0x0588;
    ctx->pc = 0x7ff6;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),$00 */
pc_7ff6:
    /* 13:7ff6 */     gb_tick(ctx, 11);
    gb_write8(ctx, ctx->hl, 0x00);
    gb_tick(ctx, 1);
    ctx->pc = 0x7ff8;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,$dad6 */
pc_7ff8:
    /* 13:7ff8 */     ctx->hl = GB_WRAMX_BASE + 0x0ad6;
    ctx->pc = 0x7ffb;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),$00 */
pc_7ffb:
    /* 13:7ffb */     gb_tick(ctx, 11);
    gb_write8(ctx, ctx->hl, 0x00);
    gb_tick(ctx, 1);
    ctx->pc = 0x7ffd;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RET */
pc_7ffd:
    /* 13:7ffd */     gbrt_timed_ret(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_13_7fce(GBContext* ctx) {
    body_13_7fce(ctx);
}

void func_13_7fee(GBContext* ctx) {
    body_13_7fce(ctx);
}

/* Shared body at 13:7ffe */
static void body_13_7ffe(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_13_7ffe:
    /* RET */
    /* 13:7ffe */     gbrt_timed_ret(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_13_7ffe(GBContext* ctx) {
    body_13_7ffe(ctx);
}

/* Shared body at 14:4000 */
static void body_14_4000(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x4000: goto loc_14_4000;
        case 0x4001: goto loc_14_4001;
        case 0x4002: goto pc_4002;
        case 0x4003: goto pc_4003;
        case 0x4004: goto pc_4004;
        case 0x4005: goto pc_4005;
        case 0x4008: goto pc_4008;
        case 0x4009: goto pc_4009;
        case 0x400a: goto pc_400a;
        case 0x400b: goto pc_400b;
        case 0x400c: goto pc_400c;
        case 0x400f: goto loc_14_400f;
        case 0x4011: goto pc_4011;
        case 0x4014: goto pc_4014;
        case 0x4016: goto pc_4016;
        case 0x4019: goto pc_4019;
        case 0x401b: goto pc_401b;
        case 0x401e: goto pc_401e;
        case 0x4020: goto pc_4020;
        case 0x4021: goto pc_4021;
        case 0x4023: goto pc_4023;
        case 0x4024: goto pc_4024;
        case 0x4025: goto pc_4025;
        case 0x4028: goto loc_14_4028;
        case 0x402a: goto pc_402a;
        default: break;
    }

loc_14_4000:
    /* LD BC,$c67f */
    /* 14:4000 */     ctx->bc = GB_WRAM0_BASE + 0x067f;
    ctx->pc = 0x4003;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,C */
pc_4003:
    /* 14:4003 */     ctx->e = ctx->c;
    ctx->pc = 0x4004;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,B */
pc_4004:
    /* 14:4004 */     ctx->d = ctx->b;
    ctx->pc = 0x4005;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,$0005 */
pc_4005:
    /* 14:4005 */     ctx->hl = 0x0005;
    ctx->pc = 0x4008;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* PUSH HL */
pc_4008:
    /* 14:4008 */     gbrt_timed_push16(ctx, ctx->hl);
    ctx->pc = 0x4009;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_4009:
    /* 14:4009 */     ctx->l = ctx->h;
    ctx->pc = 0x400a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* PUSH HL */
pc_400a:
    /* 14:400a */     gbrt_timed_push16(ctx, ctx->hl);
    ctx->pc = 0x400b;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* PUSH DE */
pc_400b:
    /* 14:400b */     gbrt_timed_push16(ctx, ctx->de);
    ctx->pc = 0x400c;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CALL $3b71 */
pc_400c:
    /* 14:400c */     gbrt_timed_call(ctx, 0x3b71, 0x400f);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    func_3b71(ctx);
    return;
    if (ctx->single_step_mode) return;
    goto loc_14_400f; /* fallthrough */
loc_14_4001:
    /* LD A,A */
    /* 14:4001 */     ctx->a = ctx->a;
    ctx->pc = 0x4002;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD A,$59 */
pc_4002:
    /* 14:4002 */     gb_add8(ctx, 0x59);
    ctx->pc = 0x4004;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,B */
    /* 14:4004 */     ctx->d = ctx->b;
    ctx->pc = 0x4005;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,$0005 */
    /* 14:4005 */     ctx->hl = 0x0005;
    ctx->pc = 0x4008;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* PUSH HL */
    /* 14:4008 */     gbrt_timed_push16(ctx, ctx->hl);
    ctx->pc = 0x4009;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
    /* 14:4009 */     ctx->l = ctx->h;
    ctx->pc = 0x400a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* PUSH HL */
    /* 14:400a */     gbrt_timed_push16(ctx, ctx->hl);
    ctx->pc = 0x400b;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* PUSH DE */
    /* 14:400b */     gbrt_timed_push16(ctx, ctx->de);
    ctx->pc = 0x400c;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CALL $3b71 */
    /* 14:400c */     gbrt_timed_call(ctx, 0x3b71, 0x400f);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    func_3b71(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_400f:
    /* ADD SP,6 */
    /* 14:400f */     gbrt_timed_add_sp(ctx, 0x4010);
    ctx->pc = 0x4011;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,$c685 */
pc_4011:
    /* 14:4011 */     ctx->hl = GB_WRAM0_BASE + 0x0685;
    ctx->pc = 0x4014;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),$00 */
pc_4014:
    /* 14:4014 */     gb_tick(ctx, 11);
    gb_write8(ctx, ctx->hl, 0x00);
    gb_tick(ctx, 1);
    ctx->pc = 0x4016;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,$c684 */
pc_4016:
    /* 14:4016 */     ctx->hl = GB_WRAM0_BASE + 0x0684;
    ctx->pc = 0x4019;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),$00 */
pc_4019:
    /* 14:4019 */     gb_tick(ctx, 11);
    gb_write8(ctx, ctx->hl, 0x00);
    gb_tick(ctx, 1);
    ctx->pc = 0x401b;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,$c686 */
pc_401b:
    /* 14:401b */     ctx->hl = GB_WRAM0_BASE + 0x0686;
    ctx->pc = 0x401e;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),$00 */
pc_401e:
    /* 14:401e */     gb_tick(ctx, 11);
    gb_write8(ctx, ctx->hl, 0x00);
    gb_tick(ctx, 1);
    ctx->pc = 0x4020;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* PUSH BC */
pc_4020:
    /* 14:4020 */     gbrt_timed_push16(ctx, ctx->bc);
    ctx->pc = 0x4021;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,$02 */
pc_4021:
    /* 14:4021 */     ctx->a = 0x02;
    ctx->pc = 0x4023;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* PUSH AF */
pc_4023:
    /* 14:4023 */     gb_pack_flags(ctx); gbrt_timed_push16(ctx, ctx->af & 0xFFF0);
    ctx->pc = 0x4024;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC SP */
pc_4024:
    /* 14:4024 */     gbrt_timed_inc16(ctx, &ctx->sp);
    ctx->pc = 0x4025;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CALL $3a56 */
pc_4025:
    /* 14:4025 */     gbrt_timed_call(ctx, 0x3a56, 0x4028);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    func_3a56(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_4028:
    /* ADD SP,3 */
    /* 14:4028 */     gbrt_timed_add_sp(ctx, 0x4029);
    ctx->pc = 0x402a;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RET */
pc_402a:
    /* 14:402a */     gbrt_timed_ret(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_14_4000(GBContext* ctx) {
    body_14_4000(ctx);
}

void func_14_4001(GBContext* ctx) {
    body_14_4000(ctx);
}

void func_14_4028(GBContext* ctx) {
    body_14_4000(ctx);
}

