/* Generated by gbrecomp from NewAdventuresofSonic */
#include "NewAdventuresofSonic_internal.h"

/* Shared body at 03:4487 */
static void body_03_4487(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x4487: goto loc_03_4487;
        case 0x448a: goto pc_448a;
        case 0x448b: goto pc_448b;
        case 0x448c: goto pc_448c;
        case 0x448e: goto pc_448e;
        case 0x448f: goto pc_448f;
        case 0x4490: goto pc_4490;
        case 0x4491: goto pc_4491;
        case 0x4494: goto loc_03_4494;
        case 0x4495: goto pc_4495;
        case 0x4497: goto pc_4497;
        case 0x4498: goto pc_4498;
        case 0x449a: goto pc_449a;
        case 0x449b: goto pc_449b;
        case 0x449c: goto pc_449c;
        case 0x449d: goto pc_449d;
        case 0x449e: goto pc_449e;
        case 0x449f: goto pc_449f;
        case 0x44a0: goto loc_03_44a0;
        case 0x44a1: goto pc_44a1;
        case 0x44a2: goto loc_03_44a2;
        case 0x44a3: goto pc_44a3;
        case 0x44a5: goto loc_03_44a5;
        case 0x44a7: goto pc_44a7;
        case 0x44a9: goto pc_44a9;
        case 0x44aa: goto pc_44aa;
        case 0x44ad: goto pc_44ad;
        case 0x44ae: goto pc_44ae;
        case 0x44af: goto pc_44af;
        case 0x44b0: goto pc_44b0;
        case 0x44b1: goto pc_44b1;
        case 0x44b2: goto pc_44b2;
        case 0x44b3: goto pc_44b3;
        case 0x44b4: goto pc_44b4;
        case 0x44b6: goto pc_44b6;
        case 0x44b7: goto pc_44b7;
        case 0x44b8: goto pc_44b8;
        case 0x44b9: goto pc_44b9;
        case 0x44ba: goto pc_44ba;
        case 0x44bb: goto pc_44bb;
        case 0x44bc: goto pc_44bc;
        case 0x44bd: goto loc_03_44bd;
        case 0x44be: goto pc_44be;
        case 0x44bf: goto pc_44bf;
        case 0x44c2: goto pc_44c2;
        case 0x44c3: goto pc_44c3;
        case 0x44c5: goto loc_03_44c5;
        case 0x44c6: goto pc_44c6;
        case 0x44c7: goto pc_44c7;
        case 0x44c8: goto pc_44c8;
        case 0x44c9: goto pc_44c9;
        case 0x44cc: goto loc_03_44cc;
        case 0x44ce: goto pc_44ce;
        case 0x44cf: goto pc_44cf;
        case 0x44d0: goto pc_44d0;
        case 0x44d2: goto loc_03_44d2;
        case 0x44d3: goto pc_44d3;
        case 0x44d6: goto loc_03_44d6;
        case 0x44d7: goto pc_44d7;
        case 0x44d8: goto pc_44d8;
        case 0x44d9: goto pc_44d9;
        case 0x44da: goto pc_44da;
        case 0x44db: goto pc_44db;
        case 0x44dc: goto pc_44dc;
        case 0x44de: goto pc_44de;
        case 0x44df: goto pc_44df;
        case 0x44e0: goto pc_44e0;
        case 0x44e1: goto pc_44e1;
        case 0x44e2: goto pc_44e2;
        case 0x44e3: goto pc_44e3;
        case 0x44e4: goto pc_44e4;
        case 0x44e5: goto pc_44e5;
        case 0x44e6: goto pc_44e6;
        case 0x44e7: goto pc_44e7;
        case 0x44ea: goto pc_44ea;
        case 0x44eb: goto pc_44eb;
        case 0x44ee: goto pc_44ee;
        case 0x44ef: goto pc_44ef;
        case 0x44f0: goto loc_03_44f0;
        case 0x44f1: goto pc_44f1;
        case 0x44f4: goto loc_03_44f4;
        case 0x44f6: goto pc_44f6;
        default: break;
    }

loc_03_4487:
    /* LD A,($c59b) */
    /* 03:4487 */     gb_tick(ctx, 15);
    ctx->a = gb_read8(ctx, GB_WRAM0_BASE + 0x059b);
    gb_tick(ctx, 1);
    ctx->pc = 0x448a;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* PUSH AF */
pc_448a:
    /* 03:448a */     gb_pack_flags(ctx); gbrt_timed_push16(ctx, ctx->af & 0xFFF0);
    ctx->pc = 0x448b;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC SP */
pc_448b:
    /* 03:448b */     gbrt_timed_inc16(ctx, &ctx->sp);
    ctx->pc = 0x448c;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,SP+14 */
pc_448c:
    /* 03:448c */     gbrt_timed_ld_hl_sp_n(ctx, 0x448d);
    ctx->pc = 0x448e;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,(HL) */
pc_448e:
    /* 03:448e */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x448f;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* PUSH AF */
pc_448f:
    /* 03:448f */     gb_pack_flags(ctx); gbrt_timed_push16(ctx, ctx->af & 0xFFF0);
    ctx->pc = 0x4490;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC SP */
pc_4490:
    /* 03:4490 */     gbrt_timed_inc16(ctx, &ctx->sp);
    ctx->pc = 0x4491;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CALL $379b */
pc_4491:
    /* 03:4491 */     gbrt_timed_call(ctx, 0x379b, 0x4494);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    func_379b(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_03_4494:
    /* POP HL */
    /* 03:4494 */     ctx->hl = gbrt_timed_pop16(ctx);
    ctx->pc = 0x4495;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,SP+12 */
pc_4495:
    /* 03:4495 */     gbrt_timed_ld_hl_sp_n(ctx, 0x4496);
    ctx->pc = 0x4497;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,(HL) */
pc_4497:
    /* 03:4497 */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x4498;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,$00 */
pc_4498:
    /* 03:4498 */     ctx->b = 0x00;
    ctx->pc = 0x449a;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD A,E */
pc_449a:
    /* 03:449a */     gb_add8(ctx, ctx->e);
    ctx->pc = 0x449b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,A */
pc_449b:
    /* 03:449b */     ctx->c = ctx->a;
    ctx->pc = 0x449c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,B */
pc_449c:
    /* 03:449c */     ctx->a = ctx->b;
    ctx->pc = 0x449d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,D */
pc_449d:
    /* 03:449d */     gb_adc8(ctx, ctx->d);
    ctx->pc = 0x449e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,A */
pc_449e:
    /* 03:449e */     ctx->b = ctx->a;
    ctx->pc = 0x449f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,($c887) */
pc_449f:
    /* 03:449f */     gb_tick(ctx, 15);
    ctx->a = gb_read8(ctx, GB_WRAM0_BASE + 0x0887);
    gb_tick(ctx, 1);
    ctx->pc = 0x44a2;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_03_44a2; /* fallthrough */
loc_03_44a0:
    /* ADD A,A */
    /* 03:44a0 */     gb_add8(ctx, ctx->a);
    ctx->pc = 0x44a1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RET Z */
pc_44a1:
    /* 03:44a1 */     if (ctx->f_z) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* Z */
    gbrt_timed_jump(ctx, 0x44a2, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_03_44a2:
    /* OR A */
    /* 03:44a2 */     gb_or8(ctx, ctx->a);
    ctx->pc = 0x44a3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR Z,45 */
pc_44a3:
    /* 03:44a3 */     if (ctx->f_z) {
        gbrt_timed_jump(ctx, 0x44d2, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_03_44d2;
    } /* Z */
    gbrt_timed_jump(ctx, 0x44a5, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_03_44a5:
    /* LD A,$01 */
    /* 03:44a5 */     ctx->a = 0x01;
    ctx->pc = 0x44a7;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LDH ($FF00+$4f),A */
pc_44a7:
    /* 03:44a7 */     gb_tick(ctx, 11);
    gb_write8(ctx, GB_IO_BASE + 0x4f, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x44a9;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,C */
pc_44a9:
    /* 03:44a9 */     ctx->a = ctx->c;
    ctx->pc = 0x44aa;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,$c596 */
pc_44aa:
    /* 03:44aa */     ctx->hl = GB_WRAM0_BASE + 0x0596;
    ctx->pc = 0x44ad;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD A,(HL) */
pc_44ad:
    /* 03:44ad */     gb_tick(ctx, 7);
    gb_add8(ctx, gb_read8(ctx, ctx->hl));
    gb_tick(ctx, 1);
    ctx->pc = 0x44ae;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC HL */
pc_44ae:
    /* 03:44ae */     gbrt_timed_inc16(ctx, &ctx->hl);
    ctx->pc = 0x44af;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,A */
pc_44af:
    /* 03:44af */     ctx->e = ctx->a;
    ctx->pc = 0x44b0;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,B */
pc_44b0:
    /* 03:44b0 */     ctx->a = ctx->b;
    ctx->pc = 0x44b1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,(HL) */
pc_44b1:
    /* 03:44b1 */     gb_tick(ctx, 7);
    gb_adc8(ctx, gb_read8(ctx, ctx->hl));
    gb_tick(ctx, 1);
    ctx->pc = 0x44b2;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,A */
pc_44b2:
    /* 03:44b2 */     ctx->d = ctx->a;
    ctx->pc = 0x44b3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* PUSH BC */
pc_44b3:
    /* 03:44b3 */     gbrt_timed_push16(ctx, ctx->bc);
    ctx->pc = 0x44b4;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,SP+13 */
pc_44b4:
    /* 03:44b4 */     gbrt_timed_ld_hl_sp_n(ctx, 0x44b5);
    ctx->pc = 0x44b6;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,(HL-) */
pc_44b6:
    /* 03:44b6 */     ctx->a = gbrt_timed_hl_read_auto(ctx, -1);
    ctx->pc = 0x44b7;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,A */
pc_44b7:
    /* 03:44b7 */     ctx->b = ctx->a;
    ctx->pc = 0x44b8;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,(HL-) */
pc_44b8:
    /* 03:44b8 */     ctx->a = gbrt_timed_hl_read_auto(ctx, -1);
    ctx->pc = 0x44b9;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,A */
pc_44b9:
    /* 03:44b9 */     ctx->c = ctx->a;
    ctx->pc = 0x44ba;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* PUSH BC */
pc_44ba:
    /* 03:44ba */     gbrt_timed_push16(ctx, ctx->bc);
    ctx->pc = 0x44bb;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,(HL-) */
pc_44bb:
    /* 03:44bb */     ctx->a = gbrt_timed_hl_read_auto(ctx, -1);
    ctx->pc = 0x44bc;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,A */
pc_44bc:
    /* 03:44bc */     ctx->b = ctx->a;
    ctx->pc = 0x44bd;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_03_44bd:
    /* LD C,(HL) */
    /* 03:44bd */     gb_tick(ctx, 7);
    ctx->c = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x44be;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* PUSH BC */
pc_44be:
    /* 03:44be */     gbrt_timed_push16(ctx, ctx->bc);
    ctx->pc = 0x44bf;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,($c59b) */
pc_44bf:
    /* 03:44bf */     gb_tick(ctx, 15);
    ctx->a = gb_read8(ctx, GB_WRAM0_BASE + 0x059b);
    gb_tick(ctx, 1);
    ctx->pc = 0x44c2;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,A */
pc_44c2:
    /* 03:44c2 */     ctx->h = ctx->a;
    ctx->pc = 0x44c3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,($c595) */
pc_44c3:
    /* 03:44c3 */     gb_tick(ctx, 15);
    ctx->a = gb_read8(ctx, GB_WRAM0_BASE + 0x0595);
    gb_tick(ctx, 1);
    ctx->pc = 0x44c6;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,A */
pc_44c6:
    /* 03:44c6 */     ctx->l = ctx->a;
    ctx->pc = 0x44c7;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* PUSH HL */
pc_44c7:
    /* 03:44c7 */     gbrt_timed_push16(ctx, ctx->hl);
    ctx->pc = 0x44c8;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* PUSH DE */
pc_44c8:
    /* 03:44c8 */     gbrt_timed_push16(ctx, ctx->de);
    ctx->pc = 0x44c9;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CALL $2518 */
pc_44c9:
    /* 03:44c9 */     gbrt_timed_call(ctx, 0x2518, 0x44cc);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    func_2518(ctx);
    return;
    if (ctx->single_step_mode) return;
    goto loc_03_44cc; /* fallthrough */
loc_03_44c5:
    /* PUSH BC */
    /* 03:44c5 */     gbrt_timed_push16(ctx, ctx->bc);
    ctx->pc = 0x44c6;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,A */
    /* 03:44c6 */     ctx->l = ctx->a;
    ctx->pc = 0x44c7;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* PUSH HL */
    /* 03:44c7 */     gbrt_timed_push16(ctx, ctx->hl);
    ctx->pc = 0x44c8;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* PUSH DE */
    /* 03:44c8 */     gbrt_timed_push16(ctx, ctx->de);
    ctx->pc = 0x44c9;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CALL $2518 */
    /* 03:44c9 */     gbrt_timed_call(ctx, 0x2518, 0x44cc);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    func_2518(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_03_44cc:
    /* ADD SP,8 */
    /* 03:44cc */     gbrt_timed_add_sp(ctx, 0x44cd);
    ctx->pc = 0x44ce;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* POP BC */
pc_44ce:
    /* 03:44ce */     ctx->bc = gbrt_timed_pop16(ctx);
    ctx->pc = 0x44cf;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* XOR A */
pc_44cf:
    /* 03:44cf */     gb_xor8(ctx, ctx->a);
    ctx->pc = 0x44d0;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LDH ($FF00+$4f),A */
pc_44d0:
    /* 03:44d0 */     gb_tick(ctx, 11);
    gb_write8(ctx, GB_IO_BASE + 0x4f, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x44d2;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_03_44d2:
    /* LD A,C */
    /* 03:44d2 */     ctx->a = ctx->c;
    ctx->pc = 0x44d3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,$c593 */
pc_44d3:
    /* 03:44d3 */     ctx->hl = GB_WRAM0_BASE + 0x0593;
    ctx->pc = 0x44d6;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_03_44d6:
    /* ADD A,(HL) */
    /* 03:44d6 */     gb_tick(ctx, 7);
    gb_add8(ctx, gb_read8(ctx, ctx->hl));
    gb_tick(ctx, 1);
    ctx->pc = 0x44d7;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC HL */
pc_44d7:
    /* 03:44d7 */     gbrt_timed_inc16(ctx, &ctx->hl);
    ctx->pc = 0x44d8;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,A */
pc_44d8:
    /* 03:44d8 */     ctx->c = ctx->a;
    ctx->pc = 0x44d9;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,B */
pc_44d9:
    /* 03:44d9 */     ctx->a = ctx->b;
    ctx->pc = 0x44da;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,(HL) */
pc_44da:
    /* 03:44da */     gb_tick(ctx, 7);
    gb_adc8(ctx, gb_read8(ctx, ctx->hl));
    gb_tick(ctx, 1);
    ctx->pc = 0x44db;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,A */
pc_44db:
    /* 03:44db */     ctx->b = ctx->a;
    ctx->pc = 0x44dc;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,SP+11 */
pc_44dc:
    /* 03:44dc */     gbrt_timed_ld_hl_sp_n(ctx, 0x44dd);
    ctx->pc = 0x44de;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,(HL-) */
pc_44de:
    /* 03:44de */     ctx->a = gbrt_timed_hl_read_auto(ctx, -1);
    ctx->pc = 0x44df;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,A */
pc_44df:
    /* 03:44df */     ctx->d = ctx->a;
    ctx->pc = 0x44e0;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,(HL-) */
pc_44e0:
    /* 03:44e0 */     ctx->a = gbrt_timed_hl_read_auto(ctx, -1);
    ctx->pc = 0x44e1;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,A */
pc_44e1:
    /* 03:44e1 */     ctx->e = ctx->a;
    ctx->pc = 0x44e2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* PUSH DE */
pc_44e2:
    /* 03:44e2 */     gbrt_timed_push16(ctx, ctx->de);
    ctx->pc = 0x44e3;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,(HL-) */
pc_44e3:
    /* 03:44e3 */     ctx->a = gbrt_timed_hl_read_auto(ctx, -1);
    ctx->pc = 0x44e4;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,A */
pc_44e4:
    /* 03:44e4 */     ctx->d = ctx->a;
    ctx->pc = 0x44e5;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,(HL) */
pc_44e5:
    /* 03:44e5 */     gb_tick(ctx, 7);
    ctx->e = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x44e6;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* PUSH DE */
pc_44e6:
    /* 03:44e6 */     gbrt_timed_push16(ctx, ctx->de);
    ctx->pc = 0x44e7;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,($c59b) */
pc_44e7:
    /* 03:44e7 */     gb_tick(ctx, 15);
    ctx->a = gb_read8(ctx, GB_WRAM0_BASE + 0x059b);
    gb_tick(ctx, 1);
    ctx->pc = 0x44ea;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,A */
pc_44ea:
    /* 03:44ea */     ctx->h = ctx->a;
    ctx->pc = 0x44eb;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,($c592) */
pc_44eb:
    /* 03:44eb */     gb_tick(ctx, 15);
    ctx->a = gb_read8(ctx, GB_WRAM0_BASE + 0x0592);
    gb_tick(ctx, 1);
    ctx->pc = 0x44ee;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,A */
pc_44ee:
    /* 03:44ee */     ctx->l = ctx->a;
    ctx->pc = 0x44ef;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* PUSH HL */
pc_44ef:
    /* 03:44ef */     gbrt_timed_push16(ctx, ctx->hl);
    ctx->pc = 0x44f0;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_03_44f0:
    /* PUSH BC */
    /* 03:44f0 */     gbrt_timed_push16(ctx, ctx->bc);
    ctx->pc = 0x44f1;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CALL $2518 */
pc_44f1:
    /* 03:44f1 */     gbrt_timed_call(ctx, 0x2518, 0x44f4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    func_2518(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_03_44f4:
    /* ADD SP,8 */
    /* 03:44f4 */     gbrt_timed_add_sp(ctx, 0x44f5);
    ctx->pc = 0x44f6;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RET */
pc_44f6:
    /* 03:44f6 */     gbrt_timed_ret(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_03_4487(GBContext* ctx) {
    body_03_4487(ctx);
}

void func_03_44a0(GBContext* ctx) {
    body_03_4487(ctx);
}

void func_03_44bd(GBContext* ctx) {
    body_03_4487(ctx);
}

void func_03_44c5(GBContext* ctx) {
    body_03_4487(ctx);
}

void func_03_44d6(GBContext* ctx) {
    body_03_4487(ctx);
}

void func_03_44f0(GBContext* ctx) {
    body_03_4487(ctx);
}

/* Shared body at 03:475e */
static void body_03_475e(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x475e: goto loc_03_475e;
        case 0x4760: goto pc_4760;
        case 0x4761: goto pc_4761;
        case 0x4762: goto loc_03_4762;
        case 0x4763: goto pc_4763;
        case 0x4764: goto pc_4764;
        case 0x4766: goto loc_03_4766;
        case 0x4767: goto pc_4767;
        case 0x476a: goto pc_476a;
        case 0x476c: goto pc_476c;
        case 0x476d: goto pc_476d;
        case 0x4770: goto loc_03_4770;
        case 0x4772: goto pc_4772;
        case 0x4773: goto pc_4773;
        case 0x4776: goto pc_4776;
        default: break;
    }

loc_03_475e:
    /* LD HL,SP+8 */
    /* 03:475e */     gbrt_timed_ld_hl_sp_n(ctx, 0x475f);
    ctx->pc = 0x4760;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,(HL) */
pc_4760:
    /* 03:4760 */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x4761;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD ($cab4),A */
pc_4761:
    /* 03:4761 */     gb_tick(ctx, 15);
    gb_write8(ctx, GB_WRAM0_BASE + 0x0ab4, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x4764;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,SP+9 */
pc_4764:
    /* 03:4764 */     gbrt_timed_ld_hl_sp_n(ctx, 0x4765);
    ctx->pc = 0x4766;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_03_4766; /* fallthrough */
loc_03_4762:
    /* OR H */
    /* 03:4762 */     gb_or8(ctx, ctx->h);
    ctx->pc = 0x4763;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JP Z,$09f8 */
pc_4763:
    /* 03:4763 */     if (ctx->f_z) {
        gbrt_timed_jump(ctx, 0x9f8, 16);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        func_09f8(ctx);
        return;
    } /* Z */
    gbrt_timed_jump(ctx, 0x4766, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_03_4766:
    /* LD A,(HL) */
    /* 03:4766 */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x4767;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD ($cab5),A */
pc_4767:
    /* 03:4767 */     gb_tick(ctx, 15);
    gb_write8(ctx, GB_WRAM0_BASE + 0x0ab5, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x476a;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,SP+10 */
pc_476a:
    /* 03:476a */     gbrt_timed_ld_hl_sp_n(ctx, 0x476b);
    ctx->pc = 0x476c;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,(HL) */
pc_476c:
    /* 03:476c */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x476d;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD ($cab6),A */
pc_476d:
    /* 03:476d */     gb_tick(ctx, 15);
    gb_write8(ctx, GB_WRAM0_BASE + 0x0ab6, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x4770;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_03_4770:
    /* LD HL,SP+11 */
    /* 03:4770 */     gbrt_timed_ld_hl_sp_n(ctx, 0x4771);
    ctx->pc = 0x4772;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,(HL) */
pc_4772:
    /* 03:4772 */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x4773;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD ($cab3),A */
pc_4773:
    /* 03:4773 */     gb_tick(ctx, 15);
    gb_write8(ctx, GB_WRAM0_BASE + 0x0ab3, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x4776;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RET */
pc_4776:
    /* 03:4776 */     gbrt_timed_ret(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_03_475e(GBContext* ctx) {
    body_03_475e(ctx);
}

void func_03_4762(GBContext* ctx) {
    body_03_475e(ctx);
}

void func_03_4770(GBContext* ctx) {
    body_03_475e(ctx);
}

/* Shared body at 03:4784 */
static void body_03_4784(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x4784: goto loc_03_4784;
        case 0x4785: goto loc_03_4785;
        default: break;
    }

loc_03_4784:
    /* RST $38 */
    /* 03:4784 */     gbrt_timed_rst(ctx, 0x38, 0x4785);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_03_4785:
    goto loc_03_4785; /* fallthrough */
}

void func_03_4784(GBContext* ctx) {
    body_03_4784(ctx);
}

/* Shared body at 03:4790 */
static void body_03_4790(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x4790: goto loc_03_4790;
        case 0x4791: goto loc_03_4791;
        default: break;
    }

loc_03_4790:
    /* RST $38 */
    /* 03:4790 */     gbrt_timed_rst(ctx, 0x38, 0x4791);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_03_4791:
    goto loc_03_4791; /* fallthrough */
}

void func_03_4790(GBContext* ctx) {
    body_03_4790(ctx);
}

/* Shared body at 03:4798 */
static void body_03_4798(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x4798: goto loc_03_4798;
        case 0x4799: goto loc_03_4799;
        default: break;
    }

loc_03_4798:
    /* RST $38 */
    /* 03:4798 */     gbrt_timed_rst(ctx, 0x38, 0x4799);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_03_4799:
    goto loc_03_4799; /* fallthrough */
}

void func_03_4798(GBContext* ctx) {
    body_03_4798(ctx);
}

/* Shared body at 03:47a8 */
static void body_03_47a8(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x47a8: goto loc_03_47a8;
        case 0x47a9: goto loc_03_47a9;
        case 0x47ab: goto pc_47ab;
        case 0x47ac: goto pc_47ac;
        case 0x47ad: goto loc_03_47ad;
        case 0x47af: goto pc_47af;
        case 0x47b0: goto pc_47b0;
        case 0x47b1: goto pc_47b1;
        case 0x47b2: goto pc_47b2;
        case 0x47b3: goto loc_03_47b3;
        case 0x47b4: goto loc_03_47b4;
        case 0x47b6: goto pc_47b6;
        case 0x47b7: goto pc_47b7;
        case 0x47b8: goto pc_47b8;
        case 0x47b9: goto loc_03_47b9;
        case 0x47ba: goto loc_03_47ba;
        case 0x47bb: goto loc_03_47bb;
        default: break;
    }

loc_03_47a8:
    /* RST $38 */
    /* 03:47a8 */     gbrt_timed_rst(ctx, 0x38, 0x47a9);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_03_47a9:
    /* CP $00 */
    /* 03:47a9 */     gb_cp8(ctx, 0x00);
    ctx->pc = 0x47ab;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_47ab:
    /* 03:47ab */     /* NOP */
    ctx->pc = 0x47ac;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC HL */
pc_47ac:
    /* 03:47ac */     gbrt_timed_dec16(ctx, &ctx->hl);
    ctx->pc = 0x47ad;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_03_47ad:
    /* CP $00 */
    /* 03:47ad */     gb_cp8(ctx, 0x00);
    ctx->pc = 0x47af;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_47af:
    /* 03:47af */     /* NOP */
    ctx->pc = 0x47b0;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,L */
pc_47b0:
    /* 03:47b0 */     ctx->c = ctx->l;
    ctx->pc = 0x47b1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_47b1:
    /* 03:47b1 */     /* NOP */
    ctx->pc = 0x47b2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC DE */
pc_47b2:
    /* 03:47b2 */     gbrt_timed_inc16(ctx, &ctx->de);
    ctx->pc = 0x47b3;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_03_47b3:
    /* RST $38 */
    /* 03:47b3 */     gbrt_timed_rst(ctx, 0x38, 0x47b4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_03_47b4:
    /* CP $ff */
    /* 03:47b4 */     gb_cp8(ctx, 0xff);
    ctx->pc = 0x47b6;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* EI */
pc_47b6:
    /* 03:47b6 */     ctx->ime_pending = 1;
    ctx->pc = 0x47b7;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC DE */
pc_47b7:
    /* 03:47b7 */     gbrt_timed_inc16(ctx, &ctx->de);
    ctx->pc = 0x47b8;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_47b8:
    /* 03:47b8 */     gbrt_timed_rst(ctx, 0x38, 0x47b9);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_03_47b9:
    /* RST $38 */
    /* 03:47b9 */     gbrt_timed_rst(ctx, 0x38, 0x47ba);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_03_47ba:
    /* RST $38 */
    /* 03:47ba */     gbrt_timed_rst(ctx, 0x38, 0x47bb);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_03_47bb:
    goto loc_03_47bb; /* fallthrough */
}

void func_03_47a8(GBContext* ctx) {
    body_03_47a8(ctx);
}

void func_03_47ad(GBContext* ctx) {
    body_03_47a8(ctx);
}

void func_03_47b3(GBContext* ctx) {
    body_03_47a8(ctx);
}

/* Shared body at 03:4e22 */
static void body_03_4e22(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_03_4e22:
    /* RET */
    /* 03:4e22 */     gbrt_timed_ret(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_03_4e22(GBContext* ctx) {
    body_03_4e22(ctx);
}

/* Shared body at 03:7fff */
static void body_03_7fff(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_03_7fff:
    goto loc_03_7fff; /* fallthrough */
}

void func_03_7fff(GBContext* ctx) {
    body_03_7fff(ctx);
}

